version: 2.1
orbs:
  ruby: circleci/ruby@2.1.0
jobs:
  build-and-test:
    macos:
      xcode: 14.3.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle update --bundler
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  # adhoc:
  #   macos:
  #     xcode: 14.3.1
  #   working_directory: /Users/distiller/project
  #   environment:
  #     FL_OUTPUT_DIR: output
  #     FASTLANE_LANE: adhoc
  #   shell: /bin/bash --login -o pipefail
  #   steps:
  #     - checkout
  #     - run: bundle install
  #     - run:
  #         name: Fastlane
  #         command: bundle exec fastlane $FASTLANE_LANE
  #     - store_artifacts:
  #         path: output/Game.ipa

  beta:
    macos:
      xcode: 14.3.1
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle update --bundler
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output/Game.ipa

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
      # - adhoc:
      #     filters:
      #       branches:
      #         only: development
      #     requires:
      #       - build-and-test
      - beta:
          filters:
            branches:
              only: master
          requires:
            - build-and-test
